import React, { useMemo, useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { Canvas, Circle, Group, Rect } from '@shopify/react-native-skia';
import { Chess } from 'chess.js';
import { GameEngine } from '@chessapex/shared';

const colors = { ink:'#0B0E14', panel:'#131923', lime:'#81B64C', light:'#D8E2EC', dark:'#5F7E88' };
const glyph: Record<string,string> = { wK:'♔',wQ:'♕',wR:'♖',wB:'♗',wN:'♘',wP:'♙',bK:'♚',bQ:'♛',bR:'♜',bB:'♝',bN:'♞',bP:'♟' };
function SkiaBoard({ fen, onSquare }: { fen:string; onSquare:(square:string)=>void }) { const chess = useMemo(()=>new Chess(fen),[fen]); const size=360, cell=size/8; return <View style={{width:size,height:size}}><Canvas style={{width:size,height:size,position:'absolute'}}>{chess.board().flatMap((rank,r)=>rank.map((piece,f)=>{ const x=f*cell,y=r*cell; const square=`${String.fromCharCode(97+f)}${8-r}`; return <Group key={square}><Rect x={x} y={y} width={cell} height={cell} color={(r+f)%2?colors.dark:colors.light} /></Group>}))}<Circle cx={0} cy={0} r={0} color="transparent" /></Canvas><View style={{position:'absolute',left:0,top:0,width:size,height:size}}>{chess.board().flatMap((rank,r)=>rank.map((piece,f)=>piece?<Text key={`piece-${f}-${r}`} pointerEvents="none" style={{position:'absolute',left:f*cell,top:r*cell+2,width:cell,height:cell,fontSize:36,textAlign:'center',color:piece.color==='w'?'#fff':'#111'}}>{glyph[`${piece.color}${piece.type.toUpperCase()}`]}</Text>:null))}</View><View style={{position:'absolute',left:0,top:0,flexDirection:'row',flexWrap:'wrap'}}>{Array.from({length:64},(_,i)=><Pressable key={i} onPress={()=>onSquare(`${String.fromCharCode(97+i%8)}${8-Math.floor(i/8)}`)} style={{width:cell,height:cell}} />)}</View></View>; }
export default function App() { const [engine]=useState(()=>new GameEngine()); const [fen,setFen]=useState(engine.snapshot.fen); const [selected,setSelected]=useState<string>(); const [hint,setHint]=useState('Tap a piece, then tap its destination.'); const tap=(square:string)=>{if(!selected){setSelected(square);return;} engine.play(selected as never,square as never).then(result=>{setFen(engine.snapshot.fen);setHint(result.feedback);setSelected(undefined)}).catch(()=>setHint('That move is illegal — look for another square.'));}; return <SafeAreaView style={styles.screen}><Text style={styles.logo}>Tactic<Text style={{color:colors.lime}}>Forge</Text></Text><Text style={styles.kicker}>DAILY FORGE · 12 MIN</Text><Text style={styles.title}>Make every move<br/>a little sharper.</Text><View style={styles.card}><SkiaBoard fen={fen} onSquare={tap}/><Text style={styles.hint}>{hint}</Text></View><View style={styles.actions}><Pressable style={styles.action}><Text>💡 Hint</Text></Pressable><Pressable style={styles.action}><Text>↶ Takeback</Text></Pressable><Pressable style={styles.action}><Text>▣ Analyse</Text></Pressable></View></SafeAreaView>; }
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.ink,padding:20},logo:{fontSize:25,fontWeight:'700',color:'#fff'},kicker:{color:colors.lime,fontSize:11,fontWeight:'700',letterSpacing:2,marginTop:48},title:{fontSize:34,fontWeight:'700',color:'#fff',marginVertical:14,lineHeight:38},card:{backgroundColor:colors.panel,borderRadius:18,padding:12,alignItems:'center'},hint:{color:'#A9B4C4',marginTop:14,textAlign:'center',minHeight:38},actions:{flexDirection:'row',justifyContent:'space-between',marginTop:18},action:{backgroundColor:'#202A38',borderRadius:12,paddingVertical:14,paddingHorizontal:13}});
