import { Chess } from 'chess.js';
import { classifyMove } from './classifier';
import { evaluateForSide, evaluateMaterial } from './MaterialEvaluator';
import { identifyOpening } from './OpeningBook';
import type { GameAnalysis, MoveAnalysis, PositionAnalysis } from './types';
import { phaseFromFen } from '../chess/phase';

export function analyzeGame(pgn: string, evaluate: (fen:string)=>Promise<number> = async (fen)=>evaluateMaterial(fen), confidence: 'engine'|'heuristic' = 'heuristic'): Promise<GameAnalysis> { return buildAnalysis(pgn,evaluate,confidence); }
async function buildAnalysis(pgn:string,evaluate:(fen:string)=>Promise<number>,confidence:'engine'|'heuristic'): Promise<GameAnalysis> { const chess=new Chess(); chess.loadPgn(pgn); const sans=chess.history(); const replay=new Chess(); const moves:MoveAnalysis[]=[]; let previous=await evaluate(replay.fen()); for(let i=0;i<sans.length;i++){ const san=sans[i] ?? ''; const before=replay.fen(); const move=replay.move(san); const after=replay.fen(); const evalAfter=await evaluate(after); const bestEval=Math.max(previous,evalAfter); const loss=Math.max(0,(move.color==='w'?bestEval-evalAfter:evalAfter-bestEval)); const classification=confidence==='heuristic' ? (loss>=150?'blunder':loss>=80?'mistake':loss>=40?'inaccuracy':'good') : classifyMove(-loss/100, loss<12); moves.push({ply:i+1,san,uci:`${move.from}${move.to}${move.promotion??''}`,fenBefore:before,fenAfter:after,side:move.color,evalBefore:previous,evalAfter,bestEval,centipawnLoss:Math.round(loss),classification,phase:phaseFromFen(after),coachNote:note(classification,move.san)}); previous=evalAfter; } const accuracy=confidence==='engine'?Math.max(0,Math.round(100-(moves.reduce((sum,m)=>sum+m.centipawnLoss,0)/Math.max(1,moves.length))*.45)):0; const counts=moves.reduce((acc,m)=>{acc[m.classification]=(acc[m.classification]??0)+1;return acc},{brilliant:0,great:0,good:0,inaccuracy:0,mistake:0,blunder:0} as Record<string,number>); const phases=moves.reduce((acc,m)=>{acc[m.phase]=(acc[m.phase]??0)+1;return acc},{} as Record<string,number>); const bestPhase=(Object.entries(phases).sort((a,b)=>b[1]-a[1])[0]?.[0]??'opening') as MoveAnalysis['phase']; const opening=identifyOpening(sans); return {pgn,moves,summary:{accuracy,confidence,avgCentipawnLoss:Math.round(moves.reduce((sum,m)=>sum+m.centipawnLoss,0)/Math.max(1,moves.length)),blunders:counts.blunder??0,mistakes:(counts.mistake??0),inaccuracies:(counts.inaccuracy??0),bestPhase,headline:opening?`You entered the ${opening.name}. Focus next on: ${opening.idea}`:'Your next edge is consistent threat-scanning before every move.'}}; }
function note(classification:string,san:string):string { if(classification==='blunder') return `${san} changed the evaluation sharply. Rebuild the habit: checks, captures, threats.`; if(classification==='mistake') return `${san} gave away part of the position. Ask what your opponent improves next.`; if(classification==='brilliant'||classification==='great') return `${san} matched a forcing idea. Notice the pattern before memorising the move.`; return `${san} kept the position playable. Compare your plan with the opponent's strongest reply.`; }
