'use client';
import { useEffect, useMemo, useState } from 'react';
import { Chess } from 'chess.js';
import { Chessboard } from 'react-chessboard';
import { GameEngine, WeakAI, analyzeGame, evaluateMaterial, type Color, type GameAnalysis } from '@chessapex/shared';

type PlayerColor = Color | 'random'; type Level = 'rookie' | 'club' | 'apex';
export interface GameConfig { color: PlayerColor; level: Level; mode: 'learning'|'play'; }
const levels: Record<Level,{label:string;elo:number;note:string}> = { rookie:{label:'Rookie',elo:650,note:'Gentle mistakes. Build confidence.'}, club:{label:'Club',elo:1000,note:'Keeps you honest.'}, apex:{label:'Apex',elo:1450,note:'Sharp, but still human.'} };

export function ChessBoard({config}: {config?: GameConfig}) {
  const [engine,setEngine]=useState(()=>new GameEngine(undefined,{weakAI:new WeakAI(levels[config?.level??'rookie'].elo)})); const [fen,setFen]=useState(engine.snapshot.fen); const [playerColor,setPlayerColor]=useState<Color>(config?.color==='b'?'b':'w'); const [level]=useState<Level>(config?.level??'rookie'); const [mode]=useState<'learning'|'play'>(config?.mode??'learning'); const [started,setStarted]=useState(false); const [help,setHelp]=useState<string>(); const [message,setMessage]=useState('Choose your side and step onto the board.'); const [thinking,setThinking]=useState(false); const [liveOpen,setLiveOpen]=useState(false); const [review,setReview]=useState<GameAnalysis>();
  const chess=useMemo(()=>new Chess(fen),[fen]); const legal=chess.moves({verbose:true}); const isPlayerTurn=chess.turn()===playerColor; const material=evaluateMaterial(fen); const phase=fen.split(' ')[5]&&Number(fen.split(' ')[5])>30?'endgame':Number(fen.split(' ')[5])>12?'middlegame':'opening';
  const refresh=(next:GameEngine)=>{setEngine(next);setFen(next.snapshot.fen);};
  const takeAiTurn=async(next=engine)=>{setThinking(true);const result=await next.playWeakAIMove();if(result){setFen(next.snapshot.fen);setMessage(`Apex AI played ${result.san}.`)}setThinking(false)};
  useEffect(()=>{if(started&&!isPlayerTurn&&!thinking&&!chess.isGameOver())void takeAiTurn()},[started,fen,playerColor]);
  const start=(color:PlayerColor=playerColor)=>{const resolved=color==='random'?(Math.random()>.5?'w':'b'):color;const next=new GameEngine(undefined,{weakAI:new WeakAI(levels[level].elo)});setPlayerColor(resolved);setStarted(true);setHelp(undefined);setReview(undefined);setMessage(resolved==='w'?'Your move. Scan checks, captures, and threats.':'The AI opens. Watch the position before you reply.');refresh(next);if(resolved==='b')void takeAiTurn(next)};
  const drop=(from:string,to:string)=>{if(!started||!isPlayerTurn||thinking){setMessage(thinking?'The AI is thinking…':'Start a game first.');return false}void(async()=>{try{const result=await engine.play(from as never,to as never);setFen(engine.snapshot.fen);setMessage(result.feedback);setHelp(undefined);setReview(undefined)}catch{setMessage('That move is not legal. Try another square.')}})();return true};
  const askHelp=()=>{const candidate=legal.find((move)=>['e4','d4','e5','d5','Nf3','Nc3'].includes(move.to)||move.san.includes('O-O'))??legal[0];if(!candidate)return;const why=candidate.san.includes('O-O')?'it gets your king safe and connects the rooks':(['e4','d4','e5','d5'].includes(candidate.to)?'it contests the centre and gives your pieces room':'it keeps a useful piece active while you scan the opponent’s reply');setHelp(`Try ${candidate.san}. It’s a teaching move because ${why}.`)};
  const runReview=async()=>{setReview(await analyzeGame(engine.pgn()))}; const styles=Object.fromEntries((isPlayerTurn?legal:[]).map((move)=>[move.to,{background:'radial-gradient(circle,#a7e8d0 0 17%,transparent 19%)'}]));
  return <section className="arena-shell"><div className="arena-top"><div><span className="mini-label">{mode==='learning'?'LEARNING MODE':'PLAY MODE'} · {levels[level].label.toUpperCase()}</span><h2>{started?(isPlayerTurn?'Your turn.':'AI is thinking.'):'Set your first climb.'}</h2></div><div className="side-picker"><button className={playerColor==='w'?'active':''} onClick={()=>setPlayerColor('w')}>White</button><button className={playerColor==='b'?'active':''} onClick={()=>setPlayerColor('b')}>Black</button></div></div><div className="board-frame"><div className="eval-soft"><span/><span/></div><div className="board"><Chessboard position={fen} boardOrientation={playerColor==='b'?'black':'white'} onPieceDrop={drop} customSquareStyles={styles} animationDuration={180}/></div></div><div className="arena-footer"><span>{thinking?'Apex is calculating a human reply…':message}</span><div className="arena-actions"><button className="soft-button" onClick={()=>setLiveOpen(!liveOpen)}>◌ Live read</button><button className="soft-button" onClick={askHelp} disabled={!started||!isPlayerTurn}>💡 Ask for help</button><button className="primary-small" onClick={()=>start(playerColor)}>{started?'New game':'Start game'} ↗</button></div></div>{liveOpen&&<div className="live-read"><span>LIVE POSITION READ</span><strong>{phase} · {material>25?'White has a material edge':material<-25?'Black has a material edge':'Material is balanced'}</strong><small>Live reads stay high-level. Ask for help when you want a concrete next move.</small></div>}{help&&<div className="help-bubble"><span>COACH NOTE</span><strong>{help}</strong></div>}{started&&<button className="review-link" onClick={runReview}>Review this game on this page →</button>}{review&&<div className="postgame-panel"><div><span>POST-GAME REVIEW</span><strong>{review.summary.confidence==='engine'?`${review.summary.accuracy}% accuracy`:'Heuristic review'}</strong></div><p>{review.summary.headline}</p><div className="review-metrics"><b>{review.summary.avgCentipawnLoss}<small>AVG CPL</small></b><b>{review.summary.mistakes}<small>MISTAKES</small></b><b>{review.summary.blunders}<small>BLUNDERS</small></b></div></div>}</section>;
}

export function GameSetup({onPreview}:{onPreview?:(config:GameConfig)=>void}){const[color,setColor]=useState<PlayerColor>('w');const[level,setLevel]=useState<Level>('rookie');const[mode,setMode]=useState<'learning'|'play'>('learning');return <div className="setup-card"><div className="setup-heading"><span className="mini-label">MAKE IT YOURS</span><h2>Your climb starts here.</h2><p>Pick a side, choose your pressure, and decide whether the coach stays quiet until you call.</p></div><div className="setup-group"><span>YOU PLAY</span><div className="choice-row">{(['w','b','random'] as PlayerColor[]).map((item)=><button key={item} className={color===item?'choice active':'choice'} onClick={()=>setColor(item)}>{item==='w'?'♙ White':item==='b'?'♟ Black':'✦ Surprise me'}</button>)}</div></div><div className="setup-group"><span>OPPONENT LEVEL</span><div className="level-row">{(Object.keys(levels) as Level[]).map((item)=><button key={item} className={level===item?'level active':'level'} onClick={()=>setLevel(item)}><b>{levels[item].label}</b><small>{levels[item].note}</small></button>)}</div></div><div className="setup-group"><span>COACHING</span><div className="choice-row"><button className={mode==='learning'?'choice active':'choice'} onClick={()=>setMode('learning')}>◈ Learning</button><button className={mode==='play'?'choice active':'choice'} onClick={()=>setMode('play')}>♘ Play only</button></div></div><button className="cta setup-cta" onClick={()=>onPreview?.({color,level,mode})}>I’m ready to climb <span>↗</span></button></div>}
