'use client';
import { useEffect, useMemo, useState } from 'react';
import { Chess } from 'chess.js';
import { Chessboard } from 'react-chessboard';
import { GameEngine, WeakAI, analyzeGame, evaluateMaterial, type Color, type GameAnalysis } from '@chessapex/shared';

type PlayerColor = Color | 'random';
type Level = 'foundation' | 'developing' | 'tactical' | 'strategic' | 'expert';
interface LevelInfo { label: string; elo: number; note: string; promise: string; }
const levels: Record<Level, LevelInfo> = {
  foundation: { label: 'Foundation', elo: 850, note: 'Learn the board and build calm habits.', promise: 'Checks, captures, threats and healthy development.' },
  developing: { label: 'Developing', elo: 1050, note: 'Make plans from principles, not guesses.', promise: 'Centre control, king safety and simple plans.' },
  tactical: { label: 'Tactical', elo: 1250, note: 'Spot patterns before they disappear.', promise: 'Forcing moves, calculation and tactical awareness.' },
  strategic: { label: 'Strategic', elo: 1450, note: 'Turn small edges into real plans.', promise: 'Structures, weak squares and better piece play.' },
  expert: { label: 'Expert', elo: 1650, note: 'Prepare, calculate and convert.', promise: 'Dynamic evaluation, endgames and practical decisions.' },
};
export interface GameConfig { color: PlayerColor; level: Level; mode: 'learning' | 'play'; }

function teachingHint(chess: Chess, legal: ReturnType<Chess['moves']>, level: Level): string {
  const move = legal.find((candidate) => candidate.san.includes('#')) ?? legal.find((candidate) => candidate.san.includes('+')) ?? legal.find((candidate) => candidate.captured) ?? legal.find((candidate) => candidate.san.includes('O-O')) ?? legal.find((candidate) => ['e4', 'd4', 'e5', 'd5'].includes(candidate.to)) ?? legal.find((candidate) => ['Nf3', 'Nc3', 'Nf6', 'Nc6'].includes(candidate.san)) ?? legal[0];
  if (!move) return 'There is no legal move to suggest yet. First check whether the game has ended.';
  const phase = chess.moveNumber() <= 10 ? 'opening' : chess.isInsufficientMaterial() ? 'endgame' : 'middlegame';
  const forcing = move.san.includes('+') || move.san.includes('#') ? 'It is forcing, so your opponent has fewer good replies.' : '';
  const capture = move.captured ? `It wins ${move.captured === 'q' ? 'the queen' : 'material'} while improving your position.` : '';
  const principle = move.san.includes('O-O') ? 'Castling solves king safety and connects your rooks.' : ['e4', 'd4', 'e5', 'd5'].includes(move.to) ? 'This contests the centre and opens lines for your pieces.' : move.san[0] === 'N' || move.san[0] === 'B' ? 'Develop a new piece, then ask what your opponent threatens before moving again.' : phase === 'endgame' ? 'In the endgame, improve the king and calculate the pawn race before committing.' : 'Keep your pieces coordinated and compare checks, captures and threats before choosing.';
  const method = level === 'foundation' ? 'Use the CCT scan: Checks, Captures, Threats.' : level === 'developing' ? 'Name the plan: improve your worst piece, secure your king, then look for a break.' : level === 'tactical' ? 'Calculate one forcing line: your move, their strongest reply, and your follow-up.' : level === 'strategic' ? 'Compare candidate moves by piece activity, pawn structure and the opponent’s counterplay.' : 'Evaluate the resulting position, not just the move: king safety, material, activity and endgame.';
  return `Try ${move.san}. ${principle} ${capture} ${forcing} ${method}`.replace(/\s+/g, ' ').trim();
}

export function ChessBoard({ config }: { config?: GameConfig }) {
  const initialLevel = config?.level ?? 'foundation';
  const [engine, setEngine] = useState(() => new GameEngine(undefined, { weakAI: new WeakAI(levels[initialLevel].elo) }));
  const [fen, setFen] = useState(engine.snapshot.fen); const [playerColor, setPlayerColor] = useState<Color>(config?.color === 'b' ? 'b' : 'w'); const [level] = useState<Level>(initialLevel); const [mode] = useState<'learning' | 'play'>(config?.mode ?? 'learning'); const [started, setStarted] = useState(false); const [help, setHelp] = useState<string>(); const [message, setMessage] = useState('Choose your side and step onto the board.'); const [thinking, setThinking] = useState(false); const [liveOpen, setLiveOpen] = useState(false); const [review, setReview] = useState<GameAnalysis>();
  const chess = useMemo(() => new Chess(fen), [fen]); const legal = chess.moves({ verbose: true }); const isPlayerTurn = chess.turn() === playerColor; const material = evaluateMaterial(fen); const moveNumber = Number(fen.split(' ')[5] ?? 1); const phase = moveNumber > 30 ? 'endgame' : moveNumber > 12 ? 'middlegame' : 'opening';
  const refresh = (next: GameEngine) => { setEngine(next); setFen(next.snapshot.fen); };
  const takeAiTurn = async (next = engine) => { setThinking(true); const result = await next.playWeakAIMove(); if (result) { setFen(next.snapshot.fen); setMessage(`Apex AI played ${result.san}.`); } setThinking(false); };
  useEffect(() => { if (started && !isPlayerTurn && !thinking && !chess.isGameOver()) void takeAiTurn(); }, [started, fen, playerColor]);
  const start = (color: PlayerColor = playerColor) => { const resolved = color === 'random' ? (Math.random() > .5 ? 'w' : 'b') : color; const next = new GameEngine(undefined, { weakAI: new WeakAI(levels[level].elo) }); setPlayerColor(resolved); setStarted(true); setHelp(undefined); setReview(undefined); setMessage(resolved === 'w' ? 'Your move. Scan checks, captures and threats.' : 'The AI opens. Watch the position before you reply.'); refresh(next); if (resolved === 'b') void takeAiTurn(next); };
  const drop = (from: string, to: string) => { if (!started || !isPlayerTurn || thinking) { setMessage(thinking ? 'The AI is thinking…' : 'Start a game first.'); return false; } void (async () => { try { const result = await engine.play(from as never, to as never); setFen(engine.snapshot.fen); setMessage(result.feedback); setHelp(undefined); setReview(undefined); } catch { setMessage('That move is not legal. Try another square.'); } })(); return true; };
  const askHelp = () => setHelp(teachingHint(chess, legal, level)); const runReview = async () => setReview(await analyzeGame(engine.pgn())); const styles = Object.fromEntries((isPlayerTurn ? legal : []).map((move) => [move.to, { background: 'radial-gradient(circle,#9ee7c7 0 16%,transparent 18%)' }]));
  return <section className="arena-shell"><div className="arena-top"><div><span className="mini-label">{mode === 'learning' ? 'LEARNING MODE' : 'PLAY MODE'} · {levels[level].label.toUpperCase()}</span><h2>{started ? (isPlayerTurn ? 'Your turn.' : 'AI is thinking.') : 'Set your first climb.'}</h2><p className="level-promise">{levels[level].promise}</p></div><div className="side-picker"><button className={playerColor === 'w' ? 'active' : ''} onClick={() => setPlayerColor('w')}>♔ <span>White</span></button><button className={playerColor === 'b' ? 'active' : ''} onClick={() => setPlayerColor('b')}>♚ <span>Black</span></button></div></div><div className="board-frame"><div className="eval-soft"><span /><span /></div><div className="board"><Chessboard position={fen} boardOrientation={playerColor === 'b' ? 'black' : 'white'} onPieceDrop={drop} customSquareStyles={styles} customDarkSquareStyle={{ backgroundColor: '#b69a78' }} customLightSquareStyle={{ backgroundColor: '#f4e4c4' }} animationDuration={180} /></div></div><div className="arena-footer"><span>{thinking ? 'Apex is calculating a thoughtful reply…' : message}</span><div className="arena-actions"><button className="soft-button" onClick={() => setLiveOpen(!liveOpen)}>◌ Live read</button><button className="soft-button" onClick={askHelp} disabled={!started || !isPlayerTurn}>💡 Ask for help</button><button className="primary-small" onClick={() => start(playerColor)}>{started ? 'New game' : 'Start game'} ↗</button></div></div>{liveOpen && <div className="live-read"><span>LIVE POSITION READ</span><strong>{phase} · {material > 25 ? 'White has a material edge' : material < -25 ? 'Black has a material edge' : 'Material is balanced'}</strong><small>Live reads stay high-level. Ask for help when you want a concrete next move.</small></div>}{help && <div className="help-bubble"><span>COACH NOTE · {levels[level].label.toUpperCase()} METHOD</span><strong>{help}</strong></div>}{started && <button className="review-link" onClick={runReview}>Review this game on this page →</button>}{review && <div className="postgame-panel"><div><span>POST-GAME REVIEW</span><strong>{review.summary.confidence === 'engine' ? `${review.summary.accuracy}% accuracy` : 'Heuristic review'}</strong></div><p>{review.summary.headline}</p><div className="review-metrics"><b>{review.summary.avgCentipawnLoss}<small>AVG CPL</small></b><b>{review.summary.mistakes}<small>MISTAKES</small></b><b>{review.summary.blunders}<small>BLUNDERS</small></b></div></div>}</section>;
}

export function GameSetup({ onPreview }: { onPreview?: (config: GameConfig) => void }) { const [color, setColor] = useState<PlayerColor>('w'); const [level, setLevel] = useState<Level>('foundation'); const [mode, setMode] = useState<'learning' | 'play'>('learning'); return <div className="setup-card"><div className="setup-heading"><span className="mini-label">CHOOSE YOUR LEVEL</span><h2>Your climb starts here.</h2><p>Your level is the learner level. Apex tunes its strength to challenge you without turning every game into a wall.</p></div><div className="setup-group"><span>YOU PLAY</span><div className="choice-row">{(['w', 'b', 'random'] as PlayerColor[]).map((item) => <button key={item} className={color === item ? 'choice active' : 'choice'} onClick={() => setColor(item)}>{item === 'w' ? '♙ White' : item === 'b' ? '♟ Black' : '✦ Surprise me'}</button>)}</div></div><div className="setup-group"><span>MY LEVEL · AI ADAPTS</span><div className="level-row">{(Object.keys(levels) as Level[]).map((item) => <button key={item} className={level === item ? 'level active' : 'level'} onClick={() => setLevel(item)}><b>{levels[item].label}</b><small>{levels[item].note} · AI {levels[item].elo}</small></button>)}</div></div><div className="setup-group"><span>COACHING</span><div className="choice-row"><button className={mode === 'learning' ? 'choice active' : 'choice'} onClick={() => setMode('learning')}>◈ Learning</button><button className={mode === 'play' ? 'choice active' : 'choice'} onClick={() => setMode('play')}>♘ Play only</button></div></div><button className="cta setup-cta" onClick={() => onPreview?.({ color, level, mode })}>I’m ready to climb <span>↗</span></button></div>; }
