'use client';
import { useMemo, useState } from 'react';
import { Chess } from 'chess.js';
import { Chessboard } from 'react-chessboard';

export interface TrainerScenario { name:string; family:string; setup:string[]; solution:string; explanation:string; method:string; }

export function MoveTrainer({scenario,onClose}:{scenario:TrainerScenario;onClose:()=>void}) {
  const initial=useMemo(()=>{const board=new Chess();scenario.setup.forEach((san)=>board.move(san));return board.fen()},[scenario]);
  const [fen,setFen]=useState(initial); const [result,setResult]=useState<'idle'|'correct'|'retry'>('idle'); const [hint,setHint]=useState(false); const [attempts,setAttempts]=useState(0);
  const board=useMemo(()=>new Chess(fen),[fen]); const legal=board.moves({verbose:true});
  const reset=()=>{setFen(initial);setResult('idle');setHint(false)};
  const drop=(from:string,to:string)=>{if(result==='correct')return false;const next=new Chess(fen);const move=next.move({from:from as never,to:to as never,promotion:'q'});if(!move)return false;setAttempts((count)=>count+1);if(move.san===scenario.solution){setFen(next.fen());setResult('correct')}else setResult('retry');return true};
  const styles=Object.fromEntries(legal.map((move)=>[move.to,{background:'radial-gradient(circle,#9ee7c7 0 16%,transparent 18%)'}]));
  return <section className="trainer-panel"><div className="trainer-head"><div><span className="mini-label">MOVE TRAINER · SOLVE FIRST</span><h2>{scenario.name}</h2><p>Find the teaching move from this position. No nudge until you ask.</p></div><button className="trainer-close" onClick={onClose}>×</button></div><div className="trainer-grid"><div className="trainer-board"><Chessboard position={fen} onPieceDrop={drop} customSquareStyles={styles} customDarkSquareStyle={{backgroundColor:'#b69a78'}} customLightSquareStyle={{backgroundColor:'#f4e4c4'}} animationDuration={180}/></div><div className="trainer-side"><span className="trainer-kicker">POSITION TASK</span><h3>What is the most principled move?</h3><p className="trainer-line">{scenario.setup.length?`${scenario.setup.join(' ')} · Your move`:'Your move'}</p>{result==='idle'&&<div className="trainer-actions"><button className="trainer-hint" onClick={()=>setHint(true)}>💡 Give me a clue</button><small>{attempts?`${attempts} attempt${attempts===1?'':'s'}`:'Take a quiet moment before moving.'}</small></div>}{hint&&result!=='correct'&&<div className="trainer-clue"><b>Clue</b><span>Use the lesson idea: develop or create the central break before making a second move with the same piece.</span></div>}{result==='retry'&&<div className="trainer-feedback retry"><b>Not quite — keep thinking.</b><span>Ask: does the move improve development, claim the centre, or answer the opponent’s plan?</span><button onClick={()=>setResult('idle')}>Try again</button></div>}{result==='correct'&&<div className="trainer-feedback correct"><b>Excellent — {scenario.solution} is the teaching move.</b><span>{scenario.explanation}</span><strong>Method: {scenario.method}</strong><button onClick={reset}>Repeat this position</button></div>}<div className="trainer-footer"><span>Original ChessApex exercise</span><button onClick={onClose}>Back to theory</button></div></div></div></section>;
}
