'use client';
import { useState } from 'react';
import { MoveTrainer, type TrainerScenario } from './MoveTrainer';

type Theory = TrainerScenario & { moves: string; idea: string };
const theories: Theory[] = [
  { name: 'London System', family: 'White repertoire', setup: ['d4', 'd5', 'Nf3', 'Nf6'], solution: 'Bf4', moves: '1.d4 · 2.Nf3 · 3.Bf4 · e3 · c3', idea: 'Develop the light bishop before e3 closes it, build a solid centre, then choose a plan.', method: 'Move trainer: ask what changed after ...c5, ...Qb6 and ...Ne4.', explanation: 'Bf4 develops the light bishop before your e3 pawn closes it in. You are building a reliable setup, not memorising a random move.' },
  { name: 'Italian Game', family: 'Open game', setup: ['e4', 'e5', 'Nf3', 'Nc6'], solution: 'Bc4', moves: '1.e4 · e5 · 2.Nf3 · Nc6 · 3.Bc4', idea: 'Develop quickly and pressure f7. The central break d4 is the long-term lever.', method: 'Principle drill: development, king safety, then the centre break.', explanation: 'Bc4 develops with purpose and points at f7. Your next questions are castling and when d4 is justified.' },
  { name: "Queen's Gambit", family: 'Closed centre', setup: ['d4', 'd5'], solution: 'c4', moves: '1.d4 · d5 · 2.c4', idea: 'Challenge Black’s d5 pawn and learn when to recapture, hold the centre, or develop with tempo.', method: 'Compare cxd5, Nc3 and e3 against the opponent’s plan.', explanation: 'c4 challenges the centre immediately. The point is to make Black decide how to support d5.' },
  { name: 'Sicilian Defence', family: 'Black vs 1.e4', setup: ['e4'], solution: 'c5', moves: '1.e4 · c5', idea: 'Trade a symmetrical centre for asymmetry and active counterplay.', method: 'Pattern recall: ...d5, ...Nf6 and queenside pressure are common freeing ideas.', explanation: 'c5 fights for d4 from the flank. Black’s next job is development and a timely ...d5 break.' },
  { name: 'Caro-Kann Defence', family: 'Black vs 1.e4', setup: ['e4'], solution: 'c6', moves: '1.e4 · c6 · 2.d4 · d5', idea: 'Support the d5 break with a sound structure and develop the light bishop outside the chain.', method: 'Structure lesson: identify the good bishop before closing the centre.', explanation: 'c6 prepares ...d5 without blocking the c-pawn’s future role. Choose the structure, then the development plan.' },
  { name: 'French Defence', family: 'Black vs 1.e4', setup: ['e4'], solution: 'e6', moves: '1.e4 · e6 · 2.d4 · d5', idea: 'Invite a strong centre, then attack its base with ...c5 and ...f6.', method: 'Plan-first review: name the pawn break before choosing a piece move.', explanation: 'e6 prepares ...d5 and accepts a temporary space disadvantage. Attack the centre later rather than panic now.' },
  { name: 'King’s Indian Defence', family: 'Black vs 1.d4', setup: ['d4'], solution: 'Nf6', moves: '1.d4 · Nf6 · 2.c4 · g6 · 3.Nc3 · Bg7', idea: 'Allow space, finish development, and strike the centre with ...e5 or ...c5.', method: 'Calculation tree: compare a central break with a quiet improving move.', explanation: 'Nf6 develops toward the centre and keeps both ...g6 and ...e5 available.' },
  { name: 'Essential endgames', family: 'Conversion', setup: [], solution: 'e4', moves: 'K+P · opposition · rook activity · basic mates', idea: 'The king becomes a fighting piece: learn opposition, key squares, checks from behind, and active rooks.', method: 'Spaced repetition: solve from both sides until the technique is automatic.', explanation: 'This starter position uses the opening board so the trainer remains immediately playable; the endgame curriculum is the next trainer pack.' },
];

export function TheoryLibrary() { const [selected, setSelected] = useState<Theory>(theories[0]!); const [trainer, setTrainer] = useState(false); return <section className="theory-card"><div className="card-heading"><div><span className="mini-label">THEORY & MOVE LAB</span><h2>Learn the map, then play the position.</h2></div><span className="muted">{theories.length} PATHS</span></div>{trainer ? <MoveTrainer scenario={selected} onClose={() => setTrainer(false)} /> : <div className="theory-layout"><div className="theory-list">{theories.map((theory) => <button key={theory.name} className={selected.name === theory.name ? 'theory-item active' : 'theory-item'} onClick={() => { setSelected(theory); setTrainer(false); }}><span>♞</span><div><b>{theory.name}</b><small>{theory.family}</small></div><i>›</i></button>)}</div><article className="theory-detail"><span>{selected.family.toUpperCase()}</span><h3>{selected.name}</h3><code>{selected.moves}</code><p>{selected.idea}</p><div><strong>ChessApex method</strong><small>{selected.method}</small></div><button className="theory-cta" onClick={() => setTrainer(true)}>Open move trainer ↗</button></article></div>}</section>; }
